version: "3"
services:
  thinkdoc:
    build:
      context: .
      args:
        EIP: x.x.x.x  # api接口IP,必须设置,可以是 IP 或者域名.
    image: think
    container_name: thinkdoc
    #restart: always
    volumes:
      - /path/to/you/dir/config:/app/config  # 请注意修改 /path/to/you/dir 为云策文档配置文件目录.
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "5001-5003:5001-5003"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql-with-think
    #restart: always
    volumes:
      - /path/to/you/dir/mysql:/var/lib/mysql # 请注意修改 /path/to/you/dir 为您要存储mysql数据的目录绝对路径.
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=Jonnyan404!
      - MYSQL_DATABASE=think
      - MYSQL_USER=jonnyan404
      - MYSQL_PASSWORD=www.mrdoc.fun
    expose:
      - "3306"
    ports:
      - "63306:3306"  # 如果不需要外部连接mysql,可注释此行+上一行.
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
# Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
#volumes:
#  thinkdoc-data:
#    driver: local
#  mysql-data:
#    driver: local
