# 开发环境配置
server:
  prefix: "/api"
  port: 5001
  collaborationPort: 5003

client:
  assetPrefix: "/"
  apiUrl: "http://localhost:5001/api"
  collaborationUrl: "ws://localhost:5003"

# 数据库配置
db:
  mysql:
    host: "127.0.0.1"
    username: "root"
    password: "root"
    database: "think"
    port: 3306
    charset: "utf8mb4"
    timezone: "+08:00"
    synchronize: true

# oss 文件存储服务
oss:
  aliyun:
    accessKeyId: "LTAI4Fc65yMwx2LR23PZwUed"
    accessKeySecret: "I0EBFxRTWLyVk674raeYgC8h1tvSqG"
    bucket: "wipi"
    https: true
    region: "oss-cn-shanghai"

# jwt 配置
jwt:
  secretkey: "zA_Think+KNOWLEDGE+WIKI+DOCUMENTS@2022"
  expiresIn: "6h"
